title: MAGI//ARCHIVE
description: A searchable archive of links from across the web
repository: timetravel0/repo_posts
future: true
baseurl: "/repo_posts"
url: "https://timetravel0.github.io"
remote_theme: pages-themes/minimal@v0.2.0
author:
  name: timetravel0
  url: https://github.com/timetravel0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
